sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: lzs

  alioss:
    access-key-id: LTAI5tRwecBoVceBgPmMPAxK
    access-key-secret: uN5QV3zVkzOsGaaUq5TNyDh12o3zYN
    bucket-name: sky-itcastforlzs
    endpoint: oss-cn-beijing.aliyuncs.com
